export default {
  "Absorbing Fury": "gladiator",
  "Aerial Lockdown": "gladiator",
  "Body Combo": "gladiator",
  "Cleave": "gladiator",
  "Crippling Cut": "gladiator",
  "Crushing Blow": "gladiator",
  "Draining Blow": "gladiator",
  "Exhausting Wave": "gladiator",
  "Wrath Strike": "gladiator",
  "Rupture": "gladiator",
  "Lockdown": "gladiator",
  "Piercing Rupture": "gladiator",
  "Mocking Blast": "gladiator",
  "Sharp Strike": "gladiator",
  "Sure Strike": "gladiator",

  "Aether Leash": "templar",
  "Blood Pact": "templar",
  "Break Power": "templar",
  "Dazing Severe Blow": "templar",
  "Wrath Strike": "templar",
  "Holy Punishment": "templar",
  "Illusion Chains": "templar",
  "Pitiless Blow": "templar",
  "Shield Bash": "templar",
  "Shield Counter": "templar",

  "Flame Fusion": "sorcerer",
  "Flame Cage": "sorcerer",
  "Flame Harpoon": "sorcerer",
  "Flame Bolt": "sorcerer",
  "Ice Chain": "sorcerer",
  "Freezing Wind": "sorcerer",
  "Aetherflame": "sorcerer",
  "Magma Eruption": "sorcerer",
  "Ember": "sorcerer",
  "Flame Spray": "sorcerer",
  "Freeze": "sorcerer",
  "Soul Freeze": "sorcerer",
  "Glacial Shard": "sorcerer",
  "Stamina Absorption": "sorcerer",

  "Erosion": "spiritmaster",
  "Vacuum Choke": "spiritmaster",
  "Magic Implosion": "spiritmaster",
  "Chain of Earth": "spiritmaster",
  "Cyclone of Wrath": "spiritmaster",
  "Stone Scour": "spiritmaster",
  "Ritual Push": "spiritmaster",
  "Infernal Pain": "spiritmaster",
  "Aegis Breaker": "spiritmaster",

  "Swift Edge": "assassin",
  "Surprise Attack": "assassin",
  "Counterattack": "assassin",
  "Rune Carve": "assassin",
  "Fang Strike": "assassin",
  "Beast Kick": "assassin",
  "Shadowfall": "assassin",
  "Ambush": "assassin",
  "Assassination": "assassin",
  "Killing Spree": "assassin",
  "Ripclaw Strike": "assassin",
  
  "Entangling Shot": "ranger",
  "Deadshot": "ranger",
  "Stunning Shot": "ranger",
  "Swift Shot": "ranger",
  "Dilation Arrow": "ranger",
  "Silence Arrow": "ranger",
  "Rupture Arrow": "ranger",
  "Gale Arrow": "ranger",
  "Shackle Arrow": "ranger",
  "Entangling Shot": "ranger",
  "Agonizing Arrow": "ranger",
  
  "Smite": "cleric",
  "Chastise": "cleric",
  "Punishing Earth": "cleric",
  "Slashing Wind": "cleric",
  "Word of Destruction": "cleric",
  "Enfeebling Burst": "cleric",
  "Thunderbolt": "cleric",
  "Earth's Wrath": "cleric",
  "Chain of Suffering": "cleric",
  "Call Lightning": "cleric",

  "Inescapable Judgement": "chanter",
  "Meteor Strike": "chanter",
  "Annihilation": "chanter",
  "Crashing Strike": "chanter",
  "Splash Swing": "chanter",
  "Incandescent Blow": "chanter",
  "Resonance Haze": "chanter",
  "Thunderbolt Strike": "chanter",
  "Disorientating Blow": "chanter",
  "Mountain Crash": "chanter",
  "Parrying Strike": "chanter",
  
  "Harassing Fire": "gunner",
  "Trunk Shot": "gunner",
  "Volley": "gunner",
  "Blazing Bombardment": "gunner",
  "Frozen Blitz": "gunner",
  "Incendiary Shell": "gunner",
  "Missile Guide": "gunner",
  "Quieting Gale": "gunner",
  "Steady Fire": "gunner",
  "Muzzle Flash": "gunner",
  "Green Grenade": "gunner",
  "Hemorrhage Shot": "gunner",
  "Juggernaut Cannon": "gunner",
  "Snow Shell": "gunner",
  "Dazzling Fire": "gunner",
  
  "Pulse": "songweaver",
  "Song of Ice": "songweaver",
  "Fiery Descant": "songweaver",
  "Syncopated Echo": "songweaver",
  "Bright Strike": "songweaver",
  "Song of Earth": "songweaver",
  "Song of Fire": "songweaver",
  "Stinging Note": "songweaver",
  "Paean of Pain": "songweaver",
  "Fiery Requiem": "songweaver",
  "Sonic Gust": "songweaver",
  "Sonic Splash": "songweaver",
  "Thronesong": "songweaver",
  "Blazing Requiem": "songweaver",
  "Treble Cleave": "songweaver",
  
  "Battery": "aethertech",
  "Bludgeon": "aethertech",
  "Chilling Wave": "aethertech",
  "Cinder Cannon": "aethertech",
  "Kinetic Slam": "aethertech",
  "Drillbore": "aethertech",
  "Riplash": "aethertech",
  "Particle Whip": "aethertech",
  "Rocket Punch": "aethertech",
  "Steel Storm": "aethertech",
  "Aetherlock Blade": "aethertech",
  "Beatdown": "aethertech",
  "Lightning Tether": "aethertech",
  "Heat Burst": "aethertech",
  "Siphoning Slash": "aethertech",
  "Sundering Blade": "aethertech",
  "Debilitating Blade": "aethertech",
  "Annihilation Barrage": "aethertech"
}